
CREATE TABLE DIM_CLIENTE (
  id_cliente INTEGER NOT NULL ,
  cliente    VARCHAR2 (255)
);

ALTER TABLE DIM_CLIENTE ADD CONSTRAINT DIM_CLIENTE_PK PRIMARY KEY ( id_cliente );

CREATE TABLE DIM_EMPLEADO(
  id_empleado INTEGER NOT NULL ,
  empleado    VARCHAR2 (255)
);

ALTER TABLE DIM_EMPLEADO ADD CONSTRAINT DIM_EMPLEADO_PK PRIMARY KEY ( id_empleado );

CREATE TABLE DIM_LAB(
  id_lab      INTEGER NOT NULL ,
  laboratorio VARCHAR2 (255)
);

ALTER TABLE DIM_LAB ADD CONSTRAINT DIM_LAB_PK PRIMARY KEY ( id_lab );

CREATE TABLE DIM_LUGAR (
  id_lugar INTEGER NOT NULL ,
  pais     VARCHAR2 (255) ,
  sucursal VARCHAR2 (255) ,
  ciudad   VARCHAR2 (255)
);

ALTER TABLE DIM_LUGAR ADD CONSTRAINT DIM_LUGAR_PK PRIMARY KEY ( id_lugar );

CREATE TABLE DIM_PRODUCTO (
  id_producto    INTEGER NOT NULL ,
  producto       VARCHAR2 (255) ,
  DIM_LAB_id_lab INTEGER NOT NULL
);

ALTER TABLE DIM_PRODUCTO ADD CONSTRAINT DIM_PRODUCTO_PK PRIMARY KEY ( id_producto );

CREATE TABLE DIM_TIEMPO (
  id_tiempo INTEGER NOT NULL ,
  dia       INTEGER ,
  mes       INTEGER ,
  año       INTEGER ,
  trimestre INTEGER ,
  venta     INTEGER
);
ALTER TABLE DIM_TIEMPO ADD CONSTRAINT DIM_TIEMPO_PK PRIMARY KEY ( id_tiempo );

CREATE TABLE HECHOS_VENTA (
  id_venta                 INTEGER NOT NULL ,
  total_vendido            NUMBER (7,2) ,
  cantidad                 INTEGER ,
  DIM_TIEMPO_id_tiempo     INTEGER NOT NULL ,
  DIM_LUGAR_id_lugar       INTEGER NOT NULL ,
  DIM_EMPLEADO_id_empleado INTEGER NOT NULL ,
  DIM_PRODUCTO_id_producto INTEGER NOT NULL ,
  DIM_CLIENTE_id_cliente   INTEGER NOT NULL
);

ALTER TABLE HECHOS_VENTA ADD CONSTRAINT HECHOS_VENTA_PK PRIMARY KEY ( id_venta );

ALTER TABLE HECHOS_VENTA ADD CONSTRAINT DIM_CLIENTE_FK FOREIGN KEY ( DIM_CLIENTE_id_cliente ) REFERENCES DIM_CLIENTE ( id_cliente );

ALTER TABLE HECHOS_VENTA ADD CONSTRAINT DIM_EMPLEADO_FK FOREIGN KEY ( DIM_EMPLEADO_id_empleado ) REFERENCES DIM_EMPLEADO ( id_empleado );

ALTER TABLE DIM_PRODUCTO ADD CONSTRAINT DIM_LAB_FK FOREIGN KEY ( DIM_LAB_id_lab ) REFERENCES DIM_LAB ( id_lab );

ALTER TABLE HECHOS_VENTA ADD CONSTRAINT DIM_LUGAR_FK FOREIGN KEY ( DIM_LUGAR_id_lugar ) REFERENCES DIM_LUGAR ( id_lugar );

ALTER TABLE HECHOS_VENTA ADD CONSTRAINT DIM_PRODUCTO_FK FOREIGN KEY ( DIM_PRODUCTO_id_producto ) REFERENCES DIM_PRODUCTO ( id_producto );

ALTER TABLE HECHOS_VENTA ADD CONSTRAINT DIM_TIEMPO_FK FOREIGN KEY ( DIM_TIEMPO_id_tiempo ) REFERENCES DIM_TIEMPO ( id_tiempo );

