
CREATE TABLE DIM_TIEMPO_VENTA (
  id_tiempo   INT NOT NULL,
  dia         INT NOT NULL,
  semana      INT NOT NULL,
  mes         INT NOT NULL,
  trimestre   INT NOT NULL,
  anio        INT NOT NULL,
  fecha_venta DATE NOT NULL
);
ALTER TABLE DIM_TIEMPO_VENTA ADD CONSTRAINT DIM_TIEMPO_PK PRIMARY KEY ( id_tiempo );

CREATE TABLE DIM_LUGAR_VENTA (
  id_lugar      INT NOT NULL,
  pais          VARCHAR (255) NOT NULL,
  ciudad        VARCHAR (255) NOT NULL,
  departamento  VARCHAR (255) NOT NULL,
  sucursal      VARCHAR (255) NOT NULL
);
ALTER TABLE DIM_LUGAR_VENTA ADD CONSTRAINT DIM_LUGAR_PK PRIMARY KEY ( id_lugar );

CREATE TABLE DIM_PRODUCTO_VENTA (
  id_producto    INT NOT NULL,
  producto       VARCHAR (255) NOT NULL,
  presentacion VARCHAR(50) NOT NULL,
  id_lab INT NOT NULL
);
ALTER TABLE DIM_PRODUCTO_VENTA ADD CONSTRAINT DIM_PRODUCTO_PK PRIMARY KEY ( id_producto );

CREATE TABLE DIM_LAB_VENTA (
  id_lab      INT NOT NULL,
  laboratorio VARCHAR (255) NOT NULL
);
ALTER TABLE DIM_LAB_VENTA ADD CONSTRAINT DIM_LAB_PK PRIMARY KEY ( id_lab );

CREATE TABLE DIM_CLIENTE_VENTA (
  id_cliente INT NOT NULL,
  cliente    VARCHAR (255) 
);
ALTER TABLE DIM_CLIENTE_VENTA ADD CONSTRAINT DIM_CLIENTE_PK PRIMARY KEY ( id_cliente );

CREATE TABLE DIM_EMPLEADO_VENTA (
  id_empleado INT NOT NULL,
  empleado    VARCHAR (255) 
);
ALTER TABLE DIM_EMPLEADO_VENTA ADD CONSTRAINT DIM_EMPLEADO_PK PRIMARY KEY ( id_empleado );

-- Tabla Principal
CREATE TABLE HECHOS_VENTA (
  id_venta      INT NOT NULL,  -- Llave Primaria
  id_tiempo     INT NOT NULL,
  id_lugar      INT NOT NULL,
  id_empleado   INT NOT NULL,
  id_cliente    INT NOT NULL,
  id_producto   INT NOT NULL,
  cantidad      INT NOT NULL,
  total_vendido FLOAT NOT NULL
);
ALTER TABLE HECHOS_VENTA ADD CONSTRAINT HECHOS_VENTA_PK PRIMARY KEY ( id_venta ); -- Llave Primaria

ALTER TABLE HECHOS_VENTA ADD CONSTRAINT DIM_TIEMPO_FK FOREIGN KEY ( id_tiempo ) REFERENCES DIM_TIEMPO_VENTA ( id_tiempo );

ALTER TABLE HECHOS_VENTA ADD CONSTRAINT DIM_LUGAR_FK FOREIGN KEY ( id_lugar ) REFERENCES DIM_LUGAR_VENTA ( id_lugar );

ALTER TABLE HECHOS_VENTA ADD CONSTRAINT DIM_EMPLEADO_FK FOREIGN KEY ( id_empleado ) REFERENCES DIM_EMPLEADO_VENTA ( id_empleado );

ALTER TABLE HECHOS_VENTA ADD CONSTRAINT DIM_CLIENTE_FK FOREIGN KEY ( id_cliente ) REFERENCES DIM_CLIENTE_VENTA ( id_cliente );

ALTER TABLE HECHOS_VENTA ADD CONSTRAINT DIM_PRODUCTO_FK FOREIGN KEY ( id_producto ) REFERENCES DIM_PRODUCTO_VENTA ( id_producto );

ALTER TABLE DIM_PRODUCTO_VENTA ADD CONSTRAINT DIM_LAB_FK FOREIGN KEY ( id_lab ) REFERENCES DIM_LAB_VENTA ( id_lab );
