INSERT INTO categoria_producto (id_categoria, categoria) VALUES (1 ,'acarbosa');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (2 ,'acenocumarol');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (3 ,'acetazolamida');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (4 ,'acetilcisteina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (5 ,'acetilsalicilato acido');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (6 ,'aciclovir');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (7 ,'acido ursodexoxicolico');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (8 ,'acitetrina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (9 ,'acth (hormona adren. hipofisaria)');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (10  ,'albendazol');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (11  ,'alendronato');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (12  ,'alopurinol');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (13  ,'aluminio hidroxido');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (14  ,'aluminio+mg. hidroxido');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (15  ,'amantadina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (16  ,'amikacina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (17  ,'aminocaproico acido');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (18  ,'aminofilina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (19  ,'amiodarona');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (20  ,'amitriptilina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (21  ,'amlodipina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (22  ,'amoxicilina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (23  ,'amoxicilina+clavulanico');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (24  ,'amoxicilina+sulbactam');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (25  ,'ampicilina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (26  ,'ampicilina+sulb. (sultamicilina)');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (27  ,'anestesico local+antibact+hem');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (28  ,'antralina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (29  ,'apraclonidina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (30  ,'atenolol');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (31  ,'atorvastatina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (32  ,'atropina sulfato');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (33  ,'auranofin');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (34  ,'aurotiosulfato sodio');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (35  ,'azatioprina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (36  ,'azitromicina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (37  ,'baclofeno');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (38  ,'beclometasona');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (39  ,'benzbromarona');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (40  ,'benzocaina+asociados');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (41  ,'benzoico acido+acido salicilico');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (42  ,'betametasona');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (43  ,'betaxolol');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (44  ,'biperideno');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (45  ,'bisacodilo');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (46  ,'bismuto hidroxido+pectina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (47  ,'bromazepan');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (48  ,'bromhexina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (49  ,'bromocriptina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (50  ,'budesonida');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (51  ,'buprenorfina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (52  ,'cabergolina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (53  ,'calamina + asociados');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (54  ,'calcio auroqueratinato');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (55  ,'calcio carbonato');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (56  ,'calcio lactogluconato');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (57  ,'calcitonina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (58  ,'calcitriol');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (59  ,'captopril');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (60  ,'carbamazepina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (61  ,'carisoprodol');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (62  ,'carvedilol');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (63  ,'cefaclor');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (64  ,'cefalexina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (65  ,'cefazolina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (66  ,'cefixima');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (67  ,'ceftazidima');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (68  ,'cefuroxima');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (69  ,'ciclopentolato');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (70  ,'ciclosporina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (71  ,'cimetidina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (72  ,'ciprofloxacina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (73  ,'cisapride');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (74  ,'claritromicina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (75  ,'clindamicina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (76  ,'clobazam');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (77  ,'clobutinol');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (78  ,'clomifeno citrato');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (79  ,'clomipramina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (80  ,'clonazepan');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (81  ,'clonidina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (82  ,'cloranfenicol');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (83  ,'clorfeniramina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (84  ,'clorfeniramina+asoc');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (85  ,'clorhexidina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (86  ,'cloroquina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (87  ,'clorpromazina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (88  ,'clortalidona');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (89  ,'clotrimazol');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (90  ,'clozapina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (91  ,'coaltar');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (92  ,'colchicina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (93  ,'colestiramina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (94  ,'colistina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (95  ,'cromoglicato disodico');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (96  ,'danazol');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (97  ,'dapsona');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (98  ,'deflazacort');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (99  ,'desferroxamina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (100 ,'desipramina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (101 ,'desmopresina acetato');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (102 ,'dexametasona');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (103 ,'dexclorfeniramina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (104 ,'dexclorfeniramina + asoc');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (105 ,'dextrometorfano');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (106 ,'dextropropoxifeno+dipirona');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (107 ,'diazepan');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (108 ,'diazoxido');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (109 ,'diclofenac');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (110 ,'diclofenac potasico');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (111 ,'diclofenac sodico');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (112 ,'dietilestilbestrol');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (113 ,'difenhidramina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (114 ,'difenilhidantoina (fenitoina)');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (115 ,'difenilhidantoina+fenobarbital');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (116 ,'digoxina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (117 ,'dihidroergotoxina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (118 ,'diltiazem');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (119 ,'dimenhidrinato');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (120 ,'dipirona');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (121 ,'divalproato sodico');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (122 ,'dnasa hna recombinante');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (123 ,'dorzolamida');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (124 ,'doxazosin');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (125 ,'doxiciclina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (126 ,'duarsob + asoc');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (127 ,'enalapril');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (128 ,'enzimas pancreaticas');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (129 ,'ergonovina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (130 ,'ergotamina+cafeina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (131 ,'eritromicina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (132 ,'eritropoyetina recombinate hna');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (133 ,'espiramicina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (134 ,'espironolactona');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (135 ,'estradiol');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (136 ,'estradiol+medroxiprogesterona');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (137 ,'estriol');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (138 ,'estrogenos conj+medroxiprog');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (139 ,'estrogenos conjugados');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (140 ,'etambutol');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (141 ,'etilefrina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (142 ,'etinilestradiol+norgestrel');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (143 ,'etosuximida');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (144 ,'factor ix');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (145 ,'factor viii');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (146 ,'felbamato');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (147 ,'fenilefrina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (148 ,'fenobarbital');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (149 ,'fenoterol');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (150 ,'fenoximetilpenicilina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (151 ,'fentanilo');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (152 ,'finasteride');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (153 ,'flecainida');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (154 ,'fluconazol');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (155 ,'flunitrazepan');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (156 ,'fluorometolona');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (157 ,'fluoxetina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (158 ,'folico acido');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (159 ,'furazolidona');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (160 ,'furosemida');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (161 ,'gabapentin');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (162 ,'gammaglobulina anti hepatitis b');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (163 ,'gammaglobulina antirrabica');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (164 ,'gammaglobulina antitetanica');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (165 ,'gammaglobulina humana');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (166 ,'gammaglobulina polivalente');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (167 ,'ganciclovir');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (168 ,'gemfibrozil');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (169 ,'gentamicina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (170 ,'gestrinona');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (171 ,'glibenclamida');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (172 ,'glipizida');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (173 ,'gonadotrofina corionica humana');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (174 ,'gonadotrofina menopausica hna (fsh+lh)');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (175 ,'griseofulvina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (176 ,'haloperidol');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (177 ,'heparina de bajo peso molecular');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (178 ,'hidroclorotiazida');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (179 ,'hidroclorotiazida+amilorida');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (180 ,'hidrocortisona');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (181 ,'hidrocortisona+acetico');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (182 ,'hidroxicina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (183 ,'hidroxicloroquina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (184 ,'hidroxiprogesterona');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (185 ,'hidroxipropilmetilcelulosa+asoc');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (186 ,'hierro sales');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (187 ,'hierro sulfato');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (188 ,'hierro+ac.folico');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (189 ,'hioscina n butil br.');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (190 ,'homatropina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (191 ,'hormona foliculoestimulante (fsh)');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (192 ,'hormona liberad. de tirotropina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (193 ,'ibuprofeno');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (194 ,'idoxuridina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (195 ,'imipramina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (196 ,'indometacina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (197 ,'inmunoglobulina anti rhd');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (198 ,'inmunoglobulina polivalente');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (199 ,'insulina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (200 ,'interferon alfa + ribavirin');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (201 ,'interferon beta');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (202 ,'ipratropio br.');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (203 ,'isoniazida');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (204 ,'isosorbide 5-mononitrato');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (205 ,'isosorbide dinitrato');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (206 ,'isotretinoina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (207 ,'isoxsuprina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (208 ,'itraconazol');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (209 ,'ketoconazol');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (210 ,'lactulosa');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (211 ,'lamotrigina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (212 ,'lanzoprazol');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (213 ,'latanoprost');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (214 ,'leche especial');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (215 ,'leche maternizada');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (216 ,'leflunomida');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (217 ,'leuprolide acetato');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (218 ,'levodopa+benserazida');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (219 ,'levodopa+carbidopa');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (220 ,'levomepromazina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (221 ,'levonorgestrel+estradiol');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (222 ,'levotiroxina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (223 ,'lh rh');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (224 ,'lidocaina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (225 ,'liotironina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (226 ,'lisinopril');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (227 ,'litio carbonato');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (228 ,'loperamida');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (229 ,'loratadina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (230 ,'lorazepan');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (231 ,'losartan');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (232 ,'lovastatin');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (233 ,'magaldrato');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (234 ,'magnesio sales');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (235 ,'mebendazol');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (236 ,'medroxiprogesterona');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (237 ,'meperidina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (238 ,'mesalazina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (239 ,'metadona');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (240 ,'metformina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (241 ,'metildopa');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (242 ,'metilergonovina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (243 ,'metilfenidato');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (244 ,'metilprednisolona');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (245 ,'metilprednisona');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (246 ,'metimazol');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (247 ,'metoclopramida');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (248 ,'metotrexato');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (249 ,'metronidazol');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (250 ,'metronidazol+nistatina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (251 ,'mexiletina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (252 ,'micofenolato mofetil');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (253 ,'micomazol');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (254 ,'mometasona');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (255 ,'monodroga');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (256 ,'morfina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (257 ,'nafazolina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (258 ,'nalbufina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (259 ,'nandrolona');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (260 ,'naproxeno');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (261 ,'neomicina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (262 ,'nifedipina retard');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (263 ,'nifurtimox');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (264 ,'nimodipina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (265 ,'nistatina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (266 ,'nitrendipina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (267 ,'nitrofurantoina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (268 ,'nitrofurazona');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (269 ,'nitroglicerina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (270 ,'noretisterona');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (271 ,'noretisterona+etinilestradiol');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (272 ,'norfloxacina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (273 ,'nortriptilina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (274 ,'octreotida');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (275 ,'olanzapina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (276 ,'omeprazol');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (277 ,'oxacepam + asociad');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (278 ,'oxcarbazepina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (279 ,'oxibuprocaina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (280 ,'oxibutinina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (281 ,'pantoprazol');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (282 ,'paracetamol');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (283 ,'paracetamol + codeina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (284 ,'paroxetina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (285 ,'penicilamina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (286 ,'penicilina g benz');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (287 ,'penicilina g sodica');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (288 ,'pergolida');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (289 ,'pilocarpina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (290 ,'pilocarpina+timolol');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (291 ,'pirantelo pamoato');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (292 ,'pirazinamida');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (293 ,'piridostigmina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (294 ,'pirimetamina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (295 ,'pirvinio');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (296 ,'polimixina b+asociac');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (297 ,'polivitaminicos');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (298 ,'potasio cloruro');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (299 ,'potasio gluconato');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (300 ,'pravastatin');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (301 ,'praziquantel');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (302 ,'prazosin');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (303 ,'prednisona');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (304 ,'progesterona');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (305 ,'prometazina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (306 ,'propafenona');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (307 ,'propanolol');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (308 ,'proparacaina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (309 ,'psyllium');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (310 ,'quinidina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (311 ,'raloxifeno');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (312 ,'ramipril');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (313 ,'ranitidina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (314 ,'rifampicina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (315 ,'rifampicina+isoniacida');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (316 ,'riluzole');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (317 ,'risperidona');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (318 ,'ritodrine');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (319 ,'rivastigmina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (320 ,'salbutamol');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (321 ,'sales rehidratacion oral');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (322 ,'salicilico acido');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (323 ,'salmeterol');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (324 ,'sertralina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (325 ,'simeticona');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (326 ,'simvastatin');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (327 ,'sodio cloruro + asociacion');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (328 ,'sodio picosulfato');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (329 ,'somatotropina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (330 ,'sucralfato');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (331 ,'sulfadiazina de plata');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (332 ,'sulfam+trimet');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (333 ,'sulfasalazina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (334 ,'sultamicilina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (335 ,'tacrolimus');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (336 ,'tamsulosina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (337 ,'teicoplanina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (338 ,'teofilina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (339 ,'terazosin');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (340 ,'testosterona');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (341 ,'tetraciclina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (342 ,'tibolona');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (343 ,'ticlopidina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (344 ,'timolol');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (345 ,'tioridazina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (346 ,'tiras reactivas');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (347 ,'tobramicina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (348 ,'tobramicina+dexametasona');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (349 ,'topiramato');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (350 ,'tranilcipromina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (351 ,'triancinolona');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (352 ,'trifluorotimidina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (353 ,'trihexifenidilo');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (354 ,'trimebutina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (355 ,'tropicamida');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (356 ,'vacuna antihaem. influenzae b');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (357 ,'vacuna antihepatitis a');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (358 ,'vacuna antihepatitis b');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (359 ,'vacuna antiparotiditica');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (360 ,'vacuna antitetanica');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (361 ,'valproico acido');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (362 ,'vancomicina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (363 ,'verapamilo');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (364 ,'vigabatrin');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (365 ,'vitamina a');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (366 ,'vitamina adek');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (367 ,'vitamina b (complejo)');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (368 ,'vitamina b1(tiamina)');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (369 ,'vitamina b12 (cianocobalamina)');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (370 ,'vitamina b6 (piridoxina)');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (371 ,'vitamina c (ascorbico acido)');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (372 ,'vitamina d (ergocalciferol)');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (373 ,'vitamina e (alfa tocoferol)');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (374 ,'vitamina k (fitomenadiona)');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (375 ,'warfarina');
INSERT INTO categoria_producto (id_categoria, categoria) VALUES (376 ,'xilometazolina');
