insert into ciudad (id_ciudad, ciudad, id_departamento) values (1, 'Zhangbang', 13);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (2, 'Ajuda', 2);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (3, 'Quebradas', 9);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (4, 'Cottbus', 10);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (5, 'Shuangxiqiao', 4);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (6, 'Jindong', 15);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (7, 'Bartolomé Masó', 14);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (8, 'Kushk', 17);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (9, 'Panggungsari', 18);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (10, 'Lugui', 3);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (11, 'Xiaxi', 14);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (12, 'Chadi', 12);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (13, 'Junglinster', 7);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (14, 'Bakuriani', 18);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (15, 'Fayzabad', 3);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (16, 'Mansa', 9);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (17, 'Faranah', 16);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (18, 'Colmeal', 3);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (19, 'Huangrangping', 13);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (20, 'Urachiche', 18);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (21, 'Stříbro', 13);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (22, 'Cool űrhajó', 7);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (23, 'Haliut', 1);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (24, 'General Enrique Mosconi', 6);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (25, 'Banfora', 11);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (26, 'Gunajaya', 15);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (27, 'Huangli', 9);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (28, 'Thorpe', 11);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (29, 'Belopa', 1);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (30, 'Moriya', 9);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (31, 'Jiexiu', 4);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (32, 'Shenzhong', 14);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (33, 'Pakemitan', 13);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (34, 'Aughrim', 1);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (35, 'Vendas de Galizes', 2);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (36, 'Aganan', 17);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (37, 'Jenang Selatan', 15);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (38, 'Bela Vista', 7);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (39, 'Geta', 19);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (40, 'Dami', 5);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (41, 'Surulangun Rawas', 17);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (42, 'Mengxi', 16);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (43, 'Clanwilliam', 3);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (44, 'Baranowo', 7);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (45, 'Lelydorp', 8);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (46, 'Néa Tríglia', 3);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (47, 'Jianping', 5);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (48, 'Guadalupe', 11);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (49, 'Montecarlo', 8);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (50, 'Mỹ Thọ', 12);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (51, 'Houston', 3);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (52, 'Xinshiba', 2);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (53, 'Kitakyūshū', 19);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (54, 'Chicago', 20);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (55, 'Bairro', 12);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (56, 'Chong’ansi', 11);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (57, 'Dob', 16);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (58, 'Visby', 19);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (59, 'Guajará Mirim', 11);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (60, 'Haoping', 11);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (61, 'Retreat', 2);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (62, 'Cabanbanan', 11);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (63, 'Auki', 19);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (64, 'Sutukung', 8);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (65, 'Cheonan', 11);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (66, 'San Luis', 20);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (67, 'Glugur Krajan', 13);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (68, 'São João dos Patos', 15);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (69, 'Bella Vista', 6);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (70, 'Hamar', 11);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (71, 'Rust’avi', 9);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (72, 'Port Glaud', 4);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (73, 'Correia Pinto', 16);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (74, 'Aguada de Pasajeros', 6);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (75, 'Poá', 5);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (76, 'Atbasar', 7);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (77, 'Campina Grande', 4);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (78, 'Cipanas', 7);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (79, 'Cacoal', 12);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (80, 'Sil-li', 3);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (81, 'Kuwumkumambal', 7);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (82, 'Chiang Khan', 18);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (83, 'Yamaranguila', 15);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (84, 'Ditsaan', 18);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (85, 'Bayanbulag', 12);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (86, 'Berlin', 5);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (87, 'Nantai', 4);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (88, 'Avignon', 15);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (89, 'Genova', 1);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (90, 'Sergokala', 7);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (91, 'Mambi', 15);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (92, 'Sinchao', 11);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (93, 'Yuanquan', 2);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (94, 'Bhunya', 14);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (95, 'Shagamu', 7);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (96, 'Mbaké', 6);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (97, 'Mengcheng Chengguanzhen', 2);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (98, 'Gaotieling', 8);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (99, 'Los Angeles', 16);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (100, 'Arsen’yev', 13);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (101, 'Smolensk', 4);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (102, 'Karangasem', 15);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (103, 'Mairinque', 14);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (104, 'Shimanovsk', 19);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (105, 'Bangkal', 10);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (106, 'Tengah', 18);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (107, 'Shanglu', 10);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (108, 'Osh', 19);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (109, 'Chejiazhuang', 5);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (110, 'Vaiamonte', 1);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (111, 'Bangkok', 18);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (112, 'Toulouse', 19);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (113, 'Osielsko', 4);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (114, 'Lambayong', 18);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (115, 'Xi’an', 13);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (116, 'Shemonaīkha', 14);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (117, 'Veghel', 13);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (118, 'Fāqūs', 11);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (119, 'Uglegorsk', 16);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (120, 'Uyutne', 12);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (121, 'Yushang', 3);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (122, 'Kuningan', 4);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (123, 'Takokak', 7);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (124, 'Ondangwa', 12);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (125, 'Älvsjö', 3);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (126, 'Correntina', 15);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (127, 'Straldzha', 2);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (128, 'Trstenik', 15);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (129, 'Aguasay', 7);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (130, 'Ibara', 3);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (131, 'Ngadipuro', 1);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (132, 'Jaru', 13);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (133, 'Krong Pi Nang', 16);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (134, 'Tateyama', 4);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (135, 'Trzcinica', 17);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (136, 'Sidrolândia', 12);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (137, 'Biyang', 2);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (138, 'Krasnoarmiys’k', 8);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (139, 'Tinta', 12);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (140, 'Bugis', 20);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (141, 'Kalety', 1);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (142, 'Tekstil’shchiki', 12);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (143, 'Chinhoyi', 9);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (144, 'Cova da Iria', 18);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (145, 'Queimados', 2);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (146, 'Andkhōy', 16);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (147, '‘Amrān', 1);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (148, 'Zaghouan', 11);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (149, 'Pondohan', 19);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (150, 'Masingbi', 14);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (151, 'Al Qadmūs', 18);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (152, 'Stýpsi', 15);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (153, 'Maksatikha', 10);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (154, 'Los Córdobas', 3);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (155, 'Bagnères-de-Bigorre', 12);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (156, 'San Fabian', 3);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (157, 'Piracicaba', 2);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (158, 'Qujiang', 19);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (159, 'Weichanglu', 9);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (160, 'Ciudad Bolívar', 3);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (161, 'Tupaciguara', 14);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (162, 'Khvalovo', 11);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (163, 'Hualongyan', 4);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (164, 'Al Jubayl', 16);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (165, 'Novomykolayivka', 2);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (166, 'Shuangjie', 2);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (167, 'Plateliai', 11);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (168, 'Tungao', 19);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (169, 'Guandukou', 15);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (170, 'Mrgavan', 6);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (171, 'Kristiansund N', 4);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (172, 'Arnhem', 3);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (173, 'Kembangarum', 7);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (174, 'Bezhta', 11);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (175, 'Šabac', 4);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (176, 'San Lorenzo', 2);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (177, 'Tongxing', 17);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (178, 'Bojongloa', 8);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (179, 'Alvalade', 19);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (180, 'Greenwood', 12);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (181, 'Xinxing', 2);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (182, 'Santulhão', 13);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (183, 'Sanquan', 13);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (184, 'Pervomayskoye', 19);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (185, 'Dowan', 11);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (186, 'Sveg', 20);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (187, 'Pamyat’ Parizhskoy Kommuny', 7);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (188, 'Askainen', 8);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (189, 'Luojiang', 17);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (190, 'Sinŭiju', 16);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (191, 'Clermont-Ferrand', 13);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (192, 'Pousada', 17);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (193, 'Idanha-a-Nova', 19);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (194, 'Beiling', 1);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (195, 'Wagar', 18);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (196, 'Dananshan', 7);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (197, 'Shabqadar', 8);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (198, 'Bealanana', 19);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (199, 'Uinskoye', 7);
insert into ciudad (id_ciudad, ciudad, id_departamento) values (200, 'Lerum', 5);
