insert into departamento (id_departamento, departamento, id_pais) values (1, 'Pennsylvania', 1);
insert into departamento (id_departamento, departamento, id_pais) values (2, 'Texas', 2);
insert into departamento (id_departamento, departamento, id_pais) values (3, 'Virginia', 3);
insert into departamento (id_departamento, departamento, id_pais) values (4, 'Ohio', 4);
insert into departamento (id_departamento, departamento, id_pais) values (5, 'New York', 5);
insert into departamento (id_departamento, departamento, id_pais) values (6, 'Georgia', 6);
insert into departamento (id_departamento, departamento, id_pais) values (7, 'Tennessee', 7);
insert into departamento (id_departamento, departamento, id_pais) values (8, 'Oregon', 8);
insert into departamento (id_departamento, departamento, id_pais) values (9, 'Florida', 1);
insert into departamento (id_departamento, departamento, id_pais) values (10, 'New Jersey', 2);
insert into departamento (id_departamento, departamento, id_pais) values (11, 'New York', 3);
insert into departamento (id_departamento, departamento, id_pais) values (12, 'Connecticut', 4);
insert into departamento (id_departamento, departamento, id_pais) values (13, 'North Carolina', 5);
insert into departamento (id_departamento, departamento, id_pais) values (14, 'Georgia', 6);
insert into departamento (id_departamento, departamento, id_pais) values (15, 'Virginia', 7);
insert into departamento (id_departamento, departamento, id_pais) values (16, 'Michigan', 8);
insert into departamento (id_departamento, departamento, id_pais) values (17, 'California', 1);
insert into departamento (id_departamento, departamento, id_pais) values (18, 'Florida', 2);
insert into departamento (id_departamento, departamento, id_pais) values (19, 'Minnesota', 3);
insert into departamento (id_departamento, departamento, id_pais) values (20, 'Louisiana', 4);
insert into departamento (id_departamento, departamento, id_pais) values (21, 'Arizona', 5);
insert into departamento (id_departamento, departamento, id_pais) values (22, 'District of Columbia', 6);
insert into departamento (id_departamento, departamento, id_pais) values (23, 'Texas', 7);
insert into departamento (id_departamento, departamento, id_pais) values (24, 'Indiana', 8);
insert into departamento (id_departamento, departamento, id_pais) values (25, 'Nevada', 1);
insert into departamento (id_departamento, departamento, id_pais) values (26, 'California', 2);
insert into departamento (id_departamento, departamento, id_pais) values (27, 'North Carolina', 3);
insert into departamento (id_departamento, departamento, id_pais) values (28, 'Florida', 4);
insert into departamento (id_departamento, departamento, id_pais) values (29, 'California', 5);
insert into departamento (id_departamento, departamento, id_pais) values (30, 'Wisconsin', 6);
insert into departamento (id_departamento, departamento, id_pais) values (31, 'Indiana', 7);
insert into departamento (id_departamento, departamento, id_pais) values (32, 'New York', 8);
insert into departamento (id_departamento, departamento, id_pais) values (33, 'Tennessee', 1);
insert into departamento (id_departamento, departamento, id_pais) values (34, 'California', 2);
insert into departamento (id_departamento, departamento, id_pais) values (35, 'Texas', 3);
insert into departamento (id_departamento, departamento, id_pais) values (36, 'District of Columbia', 4);
insert into departamento (id_departamento, departamento, id_pais) values (37, 'Illinois', 5);
insert into departamento (id_departamento, departamento, id_pais) values (38, 'Colorado', 6);
insert into departamento (id_departamento, departamento, id_pais) values (39, 'Virginia', 7);
insert into departamento (id_departamento, departamento, id_pais) values (40, 'Illinois', 8);
insert into departamento (id_departamento, departamento, id_pais) values (41, 'Nevada', 1);
insert into departamento (id_departamento, departamento, id_pais) values (42, 'New York', 2);
insert into departamento (id_departamento, departamento, id_pais) values (43, 'Illinois', 3);
insert into departamento (id_departamento, departamento, id_pais) values (44, 'District of Columbia', 4);
insert into departamento (id_departamento, departamento, id_pais) values (45, 'Delaware', 5);
insert into departamento (id_departamento, departamento, id_pais) values (46, 'Montana', 6);
insert into departamento (id_departamento, departamento, id_pais) values (47, 'California', 7);
insert into departamento (id_departamento, departamento, id_pais) values (48, 'Texas', 8);
insert into departamento (id_departamento, departamento, id_pais) values (49, 'Utah', 1);
insert into departamento (id_departamento, departamento, id_pais) values (50, 'Indiana', 2);
insert into departamento (id_departamento, departamento, id_pais) values (51, 'Kentucky', 3);
insert into departamento (id_departamento, departamento, id_pais) values (52, 'Texas', 4);
insert into departamento (id_departamento, departamento, id_pais) values (53, 'Missouri', 5);
insert into departamento (id_departamento, departamento, id_pais) values (54, 'Texas', 6);
insert into departamento (id_departamento, departamento, id_pais) values (55, 'New York', 7);
insert into departamento (id_departamento, departamento, id_pais) values (56, 'California', 8);
insert into departamento (id_departamento, departamento, id_pais) values (57, 'New York', 1);
insert into departamento (id_departamento, departamento, id_pais) values (58, 'Oregon', 2);
insert into departamento (id_departamento, departamento, id_pais) values (59, 'District of Columbia', 3);
insert into departamento (id_departamento, departamento, id_pais) values (60, 'Alabama', 4);
insert into departamento (id_departamento, departamento, id_pais) values (61, 'Vermont', 5);
insert into departamento (id_departamento, departamento, id_pais) values (62, 'Florida', 6);
insert into departamento (id_departamento, departamento, id_pais) values (63, 'Illinois', 7);
insert into departamento (id_departamento, departamento, id_pais) values (64, 'Ohio', 8);
insert into departamento (id_departamento, departamento, id_pais) values (65, 'Florida', 1);
insert into departamento (id_departamento, departamento, id_pais) values (66, 'Pennsylvania', 2);
insert into departamento (id_departamento, departamento, id_pais) values (67, 'Arkansas', 3);
insert into departamento (id_departamento, departamento, id_pais) values (68, 'California', 4);
insert into departamento (id_departamento, departamento, id_pais) values (69, 'California', 5);
insert into departamento (id_departamento, departamento, id_pais) values (70, 'Indiana', 6);
insert into departamento (id_departamento, departamento, id_pais) values (71, 'New York', 7);
insert into departamento (id_departamento, departamento, id_pais) values (72, 'Florida', 8);
insert into departamento (id_departamento, departamento, id_pais) values (73, 'Missouri', 1);
insert into departamento (id_departamento, departamento, id_pais) values (74, 'Mississippi', 2);
insert into departamento (id_departamento, departamento, id_pais) values (75, 'Minnesota', 3);
insert into departamento (id_departamento, departamento, id_pais) values (76, 'California', 4);
insert into departamento (id_departamento, departamento, id_pais) values (77, 'New York', 5);
insert into departamento (id_departamento, departamento, id_pais) values (78, 'Georgia', 6);
insert into departamento (id_departamento, departamento, id_pais) values (79, 'Arizona', 7);
insert into departamento (id_departamento, departamento, id_pais) values (80, 'Nebraska', 8);
