insert into laboratorio (id_laboratorio, nombre_laboratorio) values (1, 'Aidarex Pharmaceuticals LLC');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (2, 'PD-Rx Pharmaceuticals, Inc.');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (3, 'Amgen Inc');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (4, 'Haun Specialty Gases, Inc.');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (5, 'Mylan Pharmaceuticals Inc.');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (6, 'Pharmacia and Upjohn Company');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (7, 'Aphena Pharma Solutions - Tennessee, LLC');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (8, 'Unichem Pharmaceuticals (USA), Inc.');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (9, 'Chattem, Inc.');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (10, 'Lake Erie Medical & Surgical Supply DBA Quality Care Products LLC');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (11, 'NeilMed Pharmaceuticals, Inc.');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (12, 'AAA Pharmaceutical, Inc.');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (13, 'Jubilant HollisterStier LLC');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (14, 'Stratus Pharamceuticals');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (15, 'Lake Erie Medical DBA Quality Care Products LLC');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (16, 'Sandoz Inc');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (17, 'Safeway');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (18, 'HANIL PHARMACEUTICAL CO., LTD.');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (19, 'Mylan Institutional LLC');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (20, 'Heel Inc');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (21, 'Nelco Laboratories, Inc.');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (22, 'Beiersdorf Inc');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (23, 'H E B');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (24, 'HPI Health Products Inc.');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (25, 'LANGE SAS');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (26, 'Preferred Pharmaceuticals, Inc.');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (27, 'Actavis Inc.');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (28, 'REMEDYREPACK INC.');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (29, 'Hospira, Inc.');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (30, 'Aurobindo Pharma Limited');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (31, 'McKesson Contract Packaging');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (32, 'Ranbaxy Pharmaceuticals Inc.');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (33, 'WOCKHARDT LIMITED');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (34, 'Aurolife Pharma LLC');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (35, 'A&Z Pharmaceutical Inc.');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (36, 'Apotheca Company');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (37, 'CVS Pharmacy');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (38, 'PD-Rx Pharmaceuticals, Inc.');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (39, 'Air Products and Chemicals, Inc.');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (40, 'Feelgood Health');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (41, 'Cardinal Health');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (42, 'HARRIS TEETER');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (43, 'Fusion Brands');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (44, 'Ventura Corporation LTD');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (45, 'Taro Pharmaceuticals U.S.A., Inc.');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (46, 'HomeopathyStore.com');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (47, 'Major Pharmaceuticals');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (48, 'SUPERVALU INC.');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (49, 'Aurolife Pharma, LLC');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (50, 'Cardinal Health');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (51, 'Unit Dose Services');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (52, 'E. Fougera & Co. a division of Fougera Pharmaceuticals Inc.');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (53, 'Glenmark Generics Inc., USA');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (54, 'Preferred Pharmaceuticals, Inc.');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (55, 'Novartis Pharmaceuticals Corporation');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (56, 'Aurobindo Pharma Limited');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (57, 'Merle Norman Cosmetics, Inc');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (58, 'Carilion Materials Management');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (59, 'China Ningbo Shangge Cosmetic Technology Corp.');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (60, 'Procter & Gamble Manufacturing Company');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (61, 'RedPharm Drug Inc.');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (62, 'Lake Erie Medical DBA Quality Care Products LLC');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (63, 'Beiersdorf Inc');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (64, 'Ventura Corporation LTD.');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (65, 'OnPoint, Inc');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (66, 'Galderma Laboratories, L.P.');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (67, 'Walgreen Company');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (68, 'Golden State Medical Supply, Inc.');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (69, 'Amerisource Bergen');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (70, 'AvKARE, Inc.');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (71, 'Cardinal Health');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (72, 'ALK-Abello, Inc.');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (73, 'Jubilant HollisterStier LLC');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (74, 'A P J Laboratories Limited');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (75, 'TOPCO ASSOCIATES LLC');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (76, 'Reckitt Benckiser LLC');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (77, 'CREEKWOOD PHARMACEUTICAL, INC,');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (78, 'ALK-Abello, Inc.');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (79, 'JCI INSTITUTE OF MEDICAL SCIENCE');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (80, 'West-Ward Pharmaceutical Corp');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (81, 'GANZ U.S.A., LLC');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (82, 'Eisai, Inc');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (83, 'A-S Medication Solutions LLC');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (84, 'Costco Wholesale Company');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (85, 'Sagent Pharmaceuticals');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (86, 'Syntrion GmbH');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (87, 'Accord Healthcare Inc.');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (88, 'Apotex Corp.');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (89, 'Publix Super Markets Inc');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (90, 'Physicians Total Care, Inc.');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (91, 'Nelco Laboratories, Inc.');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (92, 'Dalian Goodwood Medical Care Ltd.');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (93, 'Nelco Laboratories, Inc.');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (94, 'STERIS Corporation');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (95, 'Midway Importing, Inc');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (96, 'Procter and Gamble Manufacturing Company');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (97, 'Duane Reade');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (98, 'Roerig');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (99, 'Cardinal Health');
insert into laboratorio (id_laboratorio, nombre_laboratorio) values (100, 'GREEN LIFE');
