insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (1, 'Fahey, Rempel and Veum', '2355 Hansons Alley', 56);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (2, 'Jenkins-Green', '0 Caliangt Point', 10);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (3, 'Schroeder Group', '3467 Express Avenue', 80);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (4, 'Bahringer Group', '1555 Gulseth Place', 20);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (5, 'Feeney-Lind', '63 Killdeer Point', 73);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (6, 'Padberg-Wehner', '8 Union Park', 4);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (7, 'Jerde Inc', '8884 Muir Center', 55);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (8, 'Rodriguez Inc', '74 Basil Point', 41);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (9, 'Hessel Inc', '2 Norway Maple Trail', 25);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (10, 'Green Group', '80 Paget Park', 47);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (11, 'Quigley-Nicolas', '5 Pierstorff Terrace', 71);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (12, 'Marvin Inc', '3049 Jenifer Drive', 66);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (13, 'Botsford Group', '1641 Golf View Plaza', 32);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (14, 'Hettinger, Jerde and Donnelly', '673 Namekagon Circle', 69);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (15, 'Zulauf, Huel and Collins', '529 Mcbride Point', 23);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (16, 'Torp-Kutch', '1216 Farmco Drive', 71);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (17, 'Schneider-Reichel', '042 Summit Road', 42);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (18, 'Koepp LLC', '53356 Oak Valley Crossing', 9);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (19, 'Harris and Sons', '0 Bowman Way', 66);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (20, 'Gorczany LLC', '04002 Superior Point', 37);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (21, 'Price-Gutkowski', '27 Kropf Parkway', 8);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (22, 'Schuppe-Stroman', '832 Rockefeller Trail', 79);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (23, 'Wolf and Sons', '62317 Dwight Pass', 61);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (24, 'Olson, Erdman and Bechtelar', '52803 Boyd Terrace', 20);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (25, 'Schulist, Kautzer and Towne', '27193 Scofield Hill', 26);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (26, 'Towne LLC', '44 Menomonie Pass', 13);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (27, 'Will, Lubowitz and Casper', '5840 Eagan Avenue', 76);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (28, 'Barrows LLC', '7 Nevada Way', 66);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (29, 'Douglas, Kassulke and Wyman', '986 Mallard Terrace', 72);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (30, 'Jacobson LLC', '2 Annamark Drive', 19);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (31, 'Hermann-VonRueden', '1 Tennyson Pass', 12);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (32, 'Fadel, Flatley and Grady', '83 Crescent Oaks Court', 65);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (33, 'Batz Group', '60693 Warner Way', 38);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (34, 'Macejkovic-Sauer', '37 Crowley Point', 5);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (35, 'Paucek, Brakus and Aufderhar', '259 Bobwhite Court', 13);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (36, 'White-Weber', '89 Paget Center', 39);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (37, 'Heathcote Inc', '54555 Steensland Drive', 54);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (38, 'Kihn Group', '590 Prairie Rose Park', 23);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (39, 'Bednar-Kling', '43 Blackbird Road', 28);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (40, 'Konopelski, McClure and Bruen', '413 Columbus Hill', 63);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (41, 'Sanford, Wunsch and Weissnat', '2479 Dahle Way', 7);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (42, 'Von LLC', '74 Oneill Place', 2);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (43, 'Wilderman-Lueilwitz', '9060 Forster Drive', 13);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (44, 'O''Hara, Shanahan and Batz', '5 Larry Trail', 55);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (45, 'Predovic, Barrows and Stanton', '2 Manufacturers Plaza', 20);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (46, 'Von-Rodriguez', '59816 Ridgeview Court', 78);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (47, 'Hackett-Pacocha', '6 Muir Road', 17);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (48, 'Ernser-Berge', '72 Clyde Gallagher Road', 25);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (49, 'Hansen Group', '5 Waxwing Street', 59);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (50, 'Dickens-Blanda', '25174 Brickson Park Way', 54);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (51, 'Tremblay, Bernhard and Wilderman', '7 Norway Maple Center', 36);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (52, 'Hyatt Group', '2 Service Avenue', 15);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (53, 'Schamberger Group', '80378 Susan Center', 29);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (54, 'Luettgen-Powlowski', '2318 Farmco Circle', 10);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (55, 'Kuhlman-Larkin', '4 Fieldstone Court', 29);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (56, 'Reichert LLC', '6696 International Hill', 31);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (57, 'Leannon-Turner', '533 Weeping Birch Pass', 62);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (58, 'Waelchi Inc', '67023 Knutson Alley', 65);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (59, 'Herzog Group', '44 Sullivan Crossing', 24);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (60, 'O''Kon Inc', '990 Manufacturers Circle', 76);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (61, 'Gerlach, Hartmann and Goodwin', '42 Hanson Court', 16);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (62, 'Zemlak Inc', '665 Mendota Way', 15);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (63, 'Hegmann and Sons', '00927 Summerview Circle', 46);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (64, 'O''Conner-Keebler', '52546 Acker Place', 15);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (65, 'Bahringer-Cormier', '57 Memorial Place', 21);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (66, 'Wehner-Blick', '241 Cordelia Junction', 32);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (67, 'Abbott, Swaniawski and Fadel', '46 Londonderry Park', 16);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (68, 'Kuhic LLC', '618 Oakridge Way', 45);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (69, 'Smitham-Lueilwitz', '4310 Hudson Drive', 62);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (70, 'Dicki Group', '7896 Stone Corner Avenue', 14);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (71, 'Dach and Sons', '7873 Dapin Plaza', 74);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (72, 'McGlynn-Hodkiewicz', '2 Oriole Crossing', 57);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (73, 'Howe, Langworth and Tromp', '16 Prentice Junction', 77);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (74, 'West LLC', '538 Sauthoff Trail', 76);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (75, 'Heaney Inc', '9 Rowland Avenue', 20);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (76, 'Gerlach, Hammes and Lubowitz', '4 East Hill', 57);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (77, 'Kuvalis-Rice', '26745 Schmedeman Street', 16);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (78, 'Cummerata-Hessel', '0891 Columbus Circle', 64);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (79, 'Reilly-Mayert', '8635 Prentice Terrace', 42);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (80, 'Cummerata Inc', '3 Reinke Junction', 2);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (81, 'Lakin, Quigley and Kreiger', '70 Golden Leaf Court', 65);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (82, 'Feest-Lemke', '3771 Magdeline Terrace', 51);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (83, 'Schowalter, Maggio and Koelpin', '59 Dapin Crossing', 21);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (84, 'Turner LLC', '037 American Trail', 45);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (85, 'Mayer Group', '2 Katie Way', 59);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (86, 'Hauck-Olson', '4314 Elmside Street', 70);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (87, 'Hauck, Sporer and Kertzmann', '7490 Pine View Alley', 44);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (88, 'Volkman-Jaskolski', '84336 Parkside Parkway', 36);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (89, 'Wyman Inc', '2027 Oak Circle', 6);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (90, 'Streich and Sons', '9 Kropf Place', 72);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (91, 'Jacobi, Schamberger and Bauch', '6105 Fuller Park', 48);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (92, 'Turner Inc', '62 Crownhardt Parkway', 56);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (93, 'Weimann and Sons', '354 Gateway Road', 15);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (94, 'O''Hara, Reinger and Boyle', '18707 Grim Center', 31);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (95, 'DuBuque Inc', '19398 Northview Hill', 80);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (96, 'Harris Group', '01723 Prairieview Drive', 58);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (97, 'Leffler-Hagenes', '99860 Lillian Trail', 61);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (98, 'Shanahan, Kris and Treutel', '9 Magdeline Crossing', 44);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (99, 'King and Sons', '1 Valley Edge Way', 54);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (100, 'Eichmann LLC', '40697 Summer Ridge Pass', 43);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (101, 'Spinka, Wehner and Shields', '35 Mariners Cove Lane', 8);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (102, 'Buckridge-Jast', '24 Sherman Parkway', 80);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (103, 'Toy, Ondricka and Mann', '70 Fieldstone Avenue', 13);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (104, 'Hoppe-Strosin', '83109 Emmet Alley', 9);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (105, 'Kling-Ullrich', '29981 Laurel Parkway', 12);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (106, 'Weissnat Group', '14 Pond Terrace', 32);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (107, 'Grant Group', '34972 Memorial Point', 8);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (108, 'Borer-Vandervort', '55 Cherokee Crossing', 2);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (109, 'Haag-Tillman', '5 Reindahl Hill', 43);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (110, 'Metz, Emmerich and McCullough', '591 Oakridge Drive', 30);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (111, 'Koelpin-Yundt', '7 Novick Street', 41);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (112, 'Metz Inc', '3 Vernon Crossing', 77);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (113, 'Reichel, Koch and Gleason', '94725 Petterle Avenue', 22);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (114, 'Wilderman-Hane', '4 Schiller Point', 26);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (115, 'Goldner-Schaefer', '9907 Old Shore Terrace', 39);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (116, 'Bode, Mitchell and Bednar', '169 Homewood Center', 71);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (117, 'Volkman-Kuhic', '0258 Badeau Street', 73);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (118, 'Schaefer and Sons', '49185 Crownhardt Park', 58);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (119, 'Sauer, Becker and Volkman', '48868 Oak Valley Junction', 28);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (120, 'Towne-Runolfsdottir', '9045 Pleasure Alley', 58);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (121, 'Green and Sons', '99 New Castle Point', 20);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (122, 'D''Amore-White', '378 Valley Edge Lane', 44);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (123, 'Keebler, Becker and Conroy', '84 Porter Plaza', 68);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (124, 'Schuster and Sons', '04 Larry Center', 29);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (125, 'Dickinson-Borer', '5 Esker Parkway', 35);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (126, 'Feest, Feil and Gerhold', '687 Anderson Point', 80);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (127, 'Heidenreich Inc', '9 Forest Dale Street', 55);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (128, 'Harber, Purdy and Lakin', '04819 Sachs Circle', 59);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (129, 'Rogahn and Sons', '7525 8th Lane', 35);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (130, 'Bergnaum and Sons', '9 Mcguire Street', 48);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (131, 'Cartwright Inc', '514 Tomscot Park', 21);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (132, 'Marvin, Larson and Rolfson', '021 Jenifer Court', 4);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (133, 'Boehm-Rice', '7486 Mockingbird Lane', 48);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (134, 'Waters LLC', '2202 Knutson Point', 40);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (135, 'Kassulke-Funk', '586 Eagle Crest Avenue', 74);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (136, 'Jast, Glover and Kling', '4216 Moland Center', 31);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (137, 'DuBuque and Sons', '2 8th Court', 26);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (138, 'Wiza-Wisozk', '14 Hagan Pass', 53);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (139, 'Marvin, Wolf and Murazik', '53637 Eggendart Trail', 6);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (140, 'Swift Inc', '765 Sheridan Pass', 33);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (141, 'Murazik Inc', '59 Blackbird Street', 70);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (142, 'Ruecker and Sons', '257 Shelley Terrace', 42);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (143, 'Wilderman, Jaskolski and Langworth', '6363 Redwing Plaza', 45);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (144, 'Pouros, Schiller and Leuschke', '456 Westend Circle', 3);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (145, 'Bailey Inc', '7477 Burrows Alley', 59);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (146, 'Lebsack-Kassulke', '949 Lakewood Gardens Avenue', 44);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (147, 'Gaylord, Paucek and Durgan', '66172 Anhalt Drive', 44);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (148, 'Lehner-Roob', '433 Banding Street', 19);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (149, 'O''Kon Inc', '39509 Northwestern Junction', 12);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (150, 'Boehm-Green', '46 Blaine Road', 75);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (151, 'Williamson, Kihn and Torp', '6 Lakewood Gardens Junction', 25);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (152, 'Gutmann-Prosacco', '7311 Dahle Pass', 49);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (153, 'Rowe Group', '5886 Hansons Avenue', 36);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (154, 'Walsh, Baumbach and Lesch', '87667 Bayside Plaza', 74);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (155, 'Gutkowski-Pacocha', '168 Columbus Court', 11);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (156, 'Williamson LLC', '34 Mallard Lane', 7);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (157, 'Stokes LLC', '78 Reinke Avenue', 68);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (158, 'Lakin Group', '166 Hooker Way', 57);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (159, 'Rath-Kris', '627 Homewood Court', 61);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (160, 'Cassin-Kuhn', '27305 Barby Parkway', 58);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (161, 'Boyle, Shanahan and Brekke', '377 Northport Lane', 3);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (162, 'Hintz-Upton', '8772 Killdeer Hill', 23);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (163, 'Thiel, Vandervort and Waters', '217 Arizona Way', 59);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (164, 'Stanton and Sons', '1391 Kropf Road', 73);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (165, 'Cronin-Spencer', '7701 Bartelt Point', 41);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (166, 'Stanton-Runolfsson', '195 North Lane', 62);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (167, 'Miller-Tillman', '0 Sundown Parkway', 5);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (168, 'Wehner-Stark', '7 Alpine Way', 59);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (169, 'Kemmer Group', '94 Clove Lane', 12);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (170, 'Koelpin-Hansen', '2 Karstens Street', 50);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (171, 'Hammes-Kuhic', '11863 Golf Course Crossing', 65);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (172, 'Feil, Koss and Nolan', '1 Sommers Pass', 78);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (173, 'VonRueden-Gerlach', '1 Maple Wood Way', 12);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (174, 'Erdman, Klein and Erdman', '6966 Pearson Way', 12);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (175, 'Rath-Champlin', '3 Cody Trail', 58);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (176, 'Swaniawski and Sons', '196 Fulton Center', 7);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (177, 'Abshire, Ryan and Senger', '4 Shasta Crossing', 21);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (178, 'Barton-Schmeler', '22 Bowman Circle', 76);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (179, 'Friesen and Sons', '8 Declaration Crossing', 65);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (180, 'Champlin Inc', '16 Thompson Junction', 65);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (181, 'Nitzsche-Dickens', '3365 Schiller Way', 32);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (182, 'Zulauf-Upton', '601 Darwin Hill', 13);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (183, 'Robel, Miller and Abbott', '69362 Dixon Hill', 49);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (184, 'Schowalter and Sons', '74 Twin Pines Point', 61);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (185, 'Klein-Von', '76279 Sachs Terrace', 57);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (186, 'Kihn-Johns', '2986 Carpenter Pass', 42);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (187, 'Wolff LLC', '19 Petterle Pass', 3);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (188, 'Langosh and Sons', '95 Esch Hill', 58);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (189, 'Crooks Group', '84319 Namekagon Junction', 78);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (190, 'Davis, Klein and Moore', '778 Ohio Pass', 11);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (191, 'Hirthe-Ferry', '5 Randy Lane', 43);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (192, 'Wyman LLC', '1191 Straubel Terrace', 27);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (193, 'Balistreri LLC', '0 Ronald Regan Road', 45);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (194, 'Olson-Larson', '8 Bunting Center', 73);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (195, 'Grady-Schowalter', '5642 Sachtjen Trail', 34);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (196, 'Marks Group', '08423 Dawn Junction', 15);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (197, 'Hagenes-Blick', '7028 Burning Wood Parkway', 70);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (198, 'Bogisich and Sons', '4 Eagan Crossing', 27);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (199, 'Morissette-Ebert', '862 Clyde Gallagher Point', 62);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (200, 'Medhurst-Rosenbaum', '9493 Brown Place', 68);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (201, 'Romaguera, Littel and Rosenbaum', '8171 Mifflin Hill', 51);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (202, 'Lebsack, Mante and Kreiger', '90 Brickson Park Lane', 14);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (203, 'Barton and Sons', '76 Annamark Place', 30);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (204, 'Beatty-Kessler', '47188 Del Mar Road', 28);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (205, 'Collins-Stanton', '9 Donald Street', 60);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (206, 'Littel and Sons', '33 Goodland Alley', 75);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (207, 'Senger, Oberbrunner and Jacobs', '20 Bobwhite Hill', 18);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (208, 'Stokes-Jacobson', '89688 Aberg Lane', 34);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (209, 'Lind Inc', '751 Express Circle', 72);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (210, 'Treutel-Rogahn', '69 Trailsway Alley', 49);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (211, 'Hermann, Price and Johnston', '4156 Prentice Alley', 67);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (212, 'Bode, Cronin and Skiles', '3882 Springs Place', 30);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (213, 'Moen and Sons', '857 Corry Hill', 45);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (214, 'Mraz Group', '2 Victoria Point', 58);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (215, 'Moen-McClure', '21 Rowland Trail', 62);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (216, 'Boehm-Braun', '46 Westend Terrace', 48);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (217, 'Renner-Blick', '35548 Spohn Plaza', 29);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (218, 'Eichmann, Kessler and Beier', '2448 2nd Hill', 36);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (219, 'Bogisich, Herzog and Langworth', '279 Bultman Place', 74);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (220, 'Gerhold Inc', '81 Northridge Hill', 27);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (221, 'Feil Inc', '390 Maple Wood Crossing', 14);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (222, 'Johnston, Hane and Windler', '2664 Moland Center', 72);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (223, 'Harris Group', '89593 Roth Hill', 16);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (224, 'Gerhold-Stoltenberg', '6 Melrose Circle', 15);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (225, 'Greenholt Inc', '1 American Ash Street', 48);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (226, 'Daugherty LLC', '102 Truax Circle', 3);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (227, 'Kulas LLC', '99160 Pleasure Avenue', 3);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (228, 'Kovacek, Trantow and Kohler', '81495 Kennedy Crossing', 18);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (229, 'Oberbrunner LLC', '88 Warbler Crossing', 46);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (230, 'Beier, Mraz and Koch', '51734 Marquette Crossing', 69);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (231, 'Kemmer-Hoppe', '400 Ruskin Center', 39);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (232, 'Schiller-Schmitt', '6 Independence Terrace', 5);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (233, 'Schimmel and Sons', '8 Dayton Street', 16);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (234, 'Pouros and Sons', '57587 Southridge Terrace', 52);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (235, 'West Group', '45982 Reinke Avenue', 35);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (236, 'Torphy, Schmeler and Schinner', '417 Clove Avenue', 59);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (237, 'Kuhlman Inc', '9 Luster Point', 9);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (238, 'Roob and Sons', '07436 Londonderry Place', 67);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (239, 'Yost Inc', '8261 Lukken Drive', 21);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (240, 'Schneider LLC', '2 Brentwood Drive', 13);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (241, 'Yundt Group', '0577 Sachs Alley', 2);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (242, 'Blick Group', '654 Main Crossing', 26);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (243, 'Keeling-Predovic', '4 John Wall Place', 75);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (244, 'Boyle and Sons', '64 Sachs Avenue', 27);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (245, 'Marvin Group', '38 Oxford Pass', 64);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (246, 'Waelchi-Murphy', '55546 Fremont Parkway', 49);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (247, 'Jones LLC', '5 Mallard Parkway', 46);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (248, 'Toy-Lesch', '04 Monica Avenue', 27);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (249, 'Luettgen, Gerlach and Schimmel', '85 Waxwing Trail', 44);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (250, 'Murray, Pfannerstill and Hahn', '59 Kennedy Hill', 59);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (251, 'Bechtelar and Sons', '25303 Katie Parkway', 61);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (252, 'Kunze and Sons', '5 Petterle Point', 44);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (253, 'Roob, Keebler and Thompson', '8 Sundown Plaza', 54);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (254, 'Terry and Sons', '59 Garrison Place', 66);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (255, 'Nienow, Trantow and Macejkovic', '27 Raven Pass', 69);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (256, 'Willms Group', '6 Eastwood Point', 7);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (257, 'Crona, Dickinson and Stamm', '40 Sunnyside Avenue', 61);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (258, 'Abbott-Hodkiewicz', '431 Ryan Road', 47);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (259, 'Gutkowski-Rolfson', '70 Nobel Way', 16);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (260, 'Doyle, Toy and Durgan', '72 Sloan Trail', 49);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (261, 'Jakubowski-Mueller', '778 Forest Dale Street', 52);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (262, 'Murazik and Sons', '58626 Jay Junction', 69);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (263, 'Rolfson Group', '05988 Carey Way', 16);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (264, 'O''Connell LLC', '58 Arapahoe Crossing', 60);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (265, 'Upton-Hessel', '7 Schmedeman Drive', 21);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (266, 'Leuschke Inc', '13 Ridgeview Center', 16);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (267, 'Wehner, Erdman and Becker', '35614 Scott Alley', 46);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (268, 'McDermott and Sons', '2 Forest Run Street', 64);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (269, 'Effertz-Waelchi', '9239 Hanson Lane', 16);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (270, 'Streich and Sons', '64828 Thackeray Hill', 46);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (271, 'Cruickshank, Borer and Rath', '646 Namekagon Circle', 43);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (272, 'Bradtke-Zboncak', '0006 Huxley Hill', 28);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (273, 'Kertzmann Inc', '2228 Little Fleur Lane', 9);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (274, 'Hoppe-Connelly', '898 Marquette Court', 62);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (275, 'Muller, Keeling and Anderson', '9856 Cordelia Drive', 35);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (276, 'Leffler, Bergnaum and Schinner', '66857 Eliot Street', 2);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (277, 'Gutkowski-Legros', '06 Weeping Birch Lane', 35);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (278, 'Mohr, Nikolaus and Daugherty', '11 Stuart Park', 31);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (279, 'Kulas-Schimmel', '32486 Bonner Hill', 24);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (280, 'Cummerata Inc', '1 Fisk Terrace', 38);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (281, 'Kuvalis-Harris', '3 Fisk Parkway', 65);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (282, 'Ferry, Klocko and Rippin', '0267 Superior Lane', 63);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (283, 'McDermott LLC', '41422 Little Fleur Avenue', 9);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (284, 'Feeney, Nolan and Tromp', '6254 West Alley', 61);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (285, 'Hackett, Walter and Greenfelder', '3483 Eagle Crest Lane', 64);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (286, 'Gusikowski-Conn', '5 Nobel Lane', 28);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (287, 'Kassulke Group', '14 Judy Place', 40);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (288, 'Bashirian LLC', '2 Washington Hill', 64);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (289, 'Conn-Kunde', '1436 Welch Place', 75);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (290, 'Pollich, Stanton and Shanahan', '6 Harbort Circle', 74);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (291, 'Lubowitz Group', '07947 High Crossing Road', 71);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (292, 'Crona LLC', '7601 Dawn Parkway', 49);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (293, 'Gerhold-Davis', '82 Sloan Point', 57);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (294, 'Graham-Koelpin', '100 Summer Ridge Plaza', 19);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (295, 'O''Connell-Monahan', '29 Declaration Street', 64);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (296, 'Bechtelar-Pfeffer', '6 Grim Crossing', 69);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (297, 'Thompson Inc', '3755 Steensland Crossing', 76);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (298, 'Romaguera, Heller and Boyle', '74 Dahle Parkway', 35);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (299, 'Abshire-Gaylord', '1508 Westerfield Park', 48);
insert into sucursal (id_sucursal, nombre, direccion, id_ciudad) values (300, 'Hane-Dooley', '62 Crest Line Parkway', 68);
